# Generated by Django 6.0 on 2026-03-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_buddy', '0003_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=4, null=True),
        ),
    ]
