# Generated by Django 6.0 on 2026-03-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_buddy', '0004_chatmessage_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
